### ISSUE TITLE
-o can't give a output 

### ISSUE THREAD

**Issue by lizhi16** [daptrace/daptrace#1]
Hi, 

I try to use the daptrace.py, and the log shows it works well.

But I can't get its results following the command line parameters.

Could you please tell me how to solve this problem?

**Comment by lizhi16** [comment]
Oh, I find the output file in /. It seems that can't using a relative path as the parameters.

**Comment by sjp38** [comment]
Sorry for this late response.  Yes, daptrace receives only absolute path.  That said, daptrace is now developed in name of DAMON (https://damonitor.github.io).  It allows relative path.  Could you use that instead?
